### ISSUE TITLE
cannot use test or render mode

### ISSUE THREAD

**Issue by xht033** [YangRui2015/Random-network-distillation_complete#1]
When I run:
Python run_atari.py --test True --render True 
I got the error: 

Traceback (most recent call last):
  File "run_atari_bayes_no_sticky_entropy_change.py", line 226, in <module>
    main()
  File "run_atari_bayes_no_sticky_entropy_change.py", line 221, in main
    num_timesteps=args.num_timesteps, hps=hps, save_freq=args.save_freq, retrain=args.retrain, test=args.test, render=args.render)
  File "run_atari_bayes_no_sticky_entropy_change.py", line 80, in train
    info = agent.step()
  File "/home/haitao/anaconda3/envs/t2t/lib/python3.7/site-packages/baselines/logger.py", line 282, in func_wrapper
    return func(*args, **kwargs)
  File "/home/haitao/code/Python/Random-network-distillation_complete/ppo_agent.py", line 502, in step
    self.env_render(l)
  File "/home/haitao/code/Python/Random-network-distillation_complete/ppo_agent.py", line 456, in env_render
    self.I.venvs[l].render()
  File "/home/haitao/code/Python/Random-network-distillation_complete/vec_env.py", line 115, in render
    self.venv.render()
  File "/home/haitao/code/Python/Random-network-distillation_complete/vec_env.py", line 290, in render
    bigimg = tile_images(imgs)
  File "/home/haitao/code/Python/Random-network-distillation_complete/utils.py", line 55, in tile_images
    if len(array.shape) == 4 and array.shape[3] == 1:
AttributeError: 'list' object has no attribute 'shape'
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/haitao/anaconda3/envs/t2t/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)

**Comment by YangRui2015** [comment]
> When I run:
> Python run_atari.py --test True --render True
> I got the error:
> 
> Traceback (most recent call last):
> File "run_atari_bayes_no_sticky_entropy_change.py", line 226, in 
> main()
> File "run_atari_bayes_no_sticky_entropy_change.py", line 221, in main
> num_timesteps=args.num_timesteps, hps=hps, save_freq=args.save_freq, retrain=args.retrain, test=args.test, render=args.render)
> File "run_atari_bayes_no_sticky_entropy_change.py", line 80, in train
> info = agent.step()
> File "/home/haitao/anaconda3/envs/t2t/lib/python3.7/site-packages/baselines/logger.py", line 282, in func_wrapper
> return func(*args, **kwargs)
> File "/home/haitao/code/Python/Random-network-distillation_complete/ppo_agent.py", line 502, in step
> self.env_render(l)
> File "/home/haitao/code/Python/Random-network-distillation_complete/ppo_agent.py", line 456, in env_render
> self.I.venvs[l].render()
> File "/home/haitao/code/Python/Random-network-distillation_complete/vec_env.py", line 115, in render
> self.venv.render()
> File "/home/haitao/code/Python/Random-network-distillation_complete/vec_env.py", line 290, in render
> bigimg = tile_images(imgs)
> File "/home/haitao/code/Python/Random-network-distillation_complete/utils.py", line 55, in tile_images
> if len(array.shape) == 4 and array.shape[3] == 1:
> AttributeError: 'list' object has no attribute 'shape'
> ^CError in atexit._run_exitfuncs:
> Traceback (most recent call last):
> File "/home/haitao/anaconda3/envs/t2t/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
> pid, sts = os.waitpid(self.pid, flag)

I think the original code had been updated, so my code doesn't work now. If you still have problem on rendering, my suggestion is reading the code of the new code's environment class and find the interface for rendering (there are many encapsulations in the environment class).
